version: '3'

services:
  web:
    build: ./app
    command: gunicorn video_storage.wsgi:application --bind 0.0.0.0:8000 --log-level DEBUG
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery:
    build: ./app
    command: celery worker --app=video_storage --loglevel=debug
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
    volumes:
      - media_volume:/usr/src/app/mediafiles

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 1337:80
    depends_on:
      - web
    labels:
      kompose.service.type: LoadBalancer

volumes:
  postgres_data:
  static_volume:
  media_volume: