apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream django_upstream {
        server web:8000;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://django_upstream;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;
            client_max_body_size 100M;
        }

        location /staticfiles/ {
            alias /usr/src/app/staticfiles/;
        }

        location /mediafiles/ {
            alias /usr/src/app/mediafiles/;
        }

    }