# Generated by Django 3.0.8 on 2020-08-01 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='имя файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
            ],
            options={
                'verbose_name_plural': 'Загруженные видео',
            },
        ),
    ]
