# Generated by Django 3.0.8 on 2020-08-02 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000, null=True, verbose_name='имя файла')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('process_status', models.IntegerField(choices=[(1, 'Saving'), (2, 'Making preview'), (3, 'Converting'), (4, 'Compressing'), (5, 'Ready'), (999, 'Error')], default=1, verbose_name='Статус обработки')),
                ('upload_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
            ],
            options={
                'verbose_name_plural': 'Загруженные видео',
            },
        ),
        migrations.CreateModel(
            name='RecordFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.IntegerField(choices=[(0, 'Preview'), (1, 'Video'), (2, 'Archive')], default=1, verbose_name='Тип файла')),
                ('file_format', models.FileField(blank=True, null=True, upload_to='', verbose_name='Расширение')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uploader.Record', verbose_name='Запись пользователя')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoFiles',
        ),
    ]
